### ISSUE TITLE
d2l-switch-visibility RTL shows both eyes in toggle

### ISSUE THREAD

**Issue by wongvincent** [BrightspaceUI/core#1015]
When right-to-left is set, the `d2l-switch-visibility` toggle is showing both eyes in the toggle when On, which is a bit confusing.

![image](https://user-images.githubusercontent.com/8463897/102918632-1bcbce00-443c-11eb-9d5f-04ee8ffb6169.png)

**Comment by dbatiste** [comment]
I have a fix for this.  Stay tuned.
