### ISSUE TITLE
d2l-input-textarea change handler issues with TestCafe

### ISSUE THREAD

**Issue by jguann** [BrightspaceUI/core#2027]
Text entered into a `textarea` using TestCafe automation does not cause a change event which updates the value for the textarea's parent element `d2l-input-textarea`.  This needs to be resolved to make TestCafe a useful tool for D2L's lit-based pages.

Issue found by @lweber-d2l and originally discussed here: https://d2l.slack.com/archives/C01EETSNEL8/p1638908655014700 

To reproduce the issue I've created a simple web app as the test fixture: https://github.com/jguann/textarea-copypaste
See the (failing) TestCafe test here: **https://github.com/jguann/TestCafe-demo**

Unsure if this is an issue with `d2l-input-textarea` or with TestCafe. If this can't be resolved, will file an issue with TestCafe instead.

**Comment by dlockhart** [comment]
Thanks Jenny. I'm not super familiar with how TestCafe works, but does the value just get set using a JavaScript API (e.g. `elem.value = 'foo';`), or is it interacting with the element by simulating click and keyboard events?

The reason I'm asking is even standard native elements (like `<textarea>`) don't fire change events when you use their JavaScript APIs -- only when a user physically interacts with them.

**Comment by lweber-d2l** [comment]
Hi Dave, thanks for your help.  From TestCafe's [documentation](https://testcafe.io/documentation/402631/why-testcafe):
> TestCafe uses client-side automation scripts to execute in-browser actions. This is how our testing library handles asynchronous events, simulates user activity, and executes user-defined JavaScript.

I'll provide more context on the Brightspace page & dialog we're trying to automate.  The page is called Module Scheduler, and it's a customization.  The workflow is straightforward: open a dialog, populate several input fields, and click the _Save_ button.  On clicking save, there are validation checks that the required fields are populated.

There are several `<d2l-input-text>` fields.  These wrap `<input>` elements.  TestCafe's entry of data into these works as expected. ✔️ 

Then we get to a `<d2l-input-textarea>` which wraps `<textarea>`.  TestCafe types into this, then the script moves focus to another field.  Whatever was typed in doesn't make its way up to the `value` for the `<d2l-input-textarea>`.  Here is a screenshot comparing a manual run vs. a TestCafe run.  In the TestCafe run, on the left, `value` retains the placeholder value.  In the manual run, on the right, `value` takes on the value that was typed in.

![scheduleJson-value-not-taking-effect](https://user-images.githubusercontent.com/59580355/150550012-d24a596f-7576-47f1-99ce-e931f2676584.png)

So, I'm stumped on why TestCafe works with all the `<d2l-input-text>` fields but not `<d2l-input-textarea>`.  Here's a screenshot showing the dialog we're working with:

![d2l-input-text_vs_d2l-input-textarea](https://user-images.githubusercontent.com/59580355/150549981-103b36d1-e8ec-4742-9d38-5a92df2fea56.png)

**Comment by dlockhart** [comment]
Thanks for the extra context.

So let's be careful not to confuse what values you're seeing in the DOM attributes in dev tools vs. what the underlying properties contains. Attributes rarely get updated when you interact with an element -- they're typically just used to populate the initial value and then after that the property is the source of truth. Most native HTML inputs even work this way, which can be very confusing at times.

Instead, I'd have a look at the property -- right-click on the `<d2l-input-textarea>` in dev tools -> Copy -> JS Path and then paste that into the console and check its `.value` and compare it against the value of the `<textarea>`. That's what will get submitted and used for validation... or at least it should be.

**Comment by jguann** [comment]
Ahh, looks like both values are populated correctly.

![image](https://user-images.githubusercontent.com/91085894/150865660-992c1931-4809-4a9e-818d-33f72f4e5578.png)

**Comment by jguann** [comment]
Both values are also correctly populated by TestCafe for the Module Scheduler test.

![image](https://user-images.githubusercontent.com/91085894/150879486-edb1c223-c625-41bf-9724-a633c5c49032.png)

@lweber-d2l  Should I file this issue with TestCafe then?

**Comment by jguann** [comment]
So the property's values are indeed getting set, however, when I put a console log in the change handlers, it never gets hit for `d2l-input-textarea`. The change handler is hit for a regular text field, and also hit for manual runs. The screenshots below are from the demo page but the same happens for Module Scheduler.

Manual:
![image](https://user-images.githubusercontent.com/91085894/151009251-3190161a-cc2b-439e-8e3c-2c4b45aeb73b.png)

TestCafe (missing console log `handleTextareaChange`:
![image](https://user-images.githubusercontent.com/91085894/151009082-b1731138-bc3e-4e80-9fe6-7f880959b80c.png)

Not sure how the values are getting set if the change handlers don't appear to be getting hit. @dlockhart Any thoughts or insight?

**Comment by dlockhart** [comment]
Nice work investigating this so far! It's weird because we're just listening to the underlying `textarea`'s `change` event and then firing our own -- so you're saying that our `_handleChange` isn't even getting called? Typically `change` events on inputs don't actually fire until the user moves focus away (the `blur` event).

Is this demo setup you have somewhere I could play around with it?

**Comment by jguann** [comment]
That's right, the change handler for `d2l-input-textarea` doesn't seem to be getting called. Yep, I made sure to move focus away from the textareas first.

The demo setup is here to play around with: https://stackblitz.com/edit/textarea-copypaste?file=src/sample-page.js.

**Comment by lweber-d2l** [comment]
Great, thank you for confirming.

**Comment by lweber-d2l** [comment]
Great, thank you @jguann for this workaround!  I'll use it and add a TestCafe scenario that checks for successful saving of a schedule.  And thank you, @dlockhart for your insight. 👍
