### ISSUE TITLE
Links to source from the Daylight site?

### ISSUE THREAD

**Issue by cgordon-d2l** [BrightspaceUI/core#2046]
I have often found it helpful to look at source for a component that I need to subclass or try to figure out an unexpected interaction.  Since this site is dynamically created from github, is it possible to have a link to the github repo where the code lives?

**Comment by dlockhart** [comment]
I think there are? There's the "suggest an edit" link which takes you to the source README and below that there's a link to the repo:

<img width="1259" alt="Screen Shot 2022-01-27 at 9 31 20 AM" src="https://user-images.githubusercontent.com/5491151/151379317-45f84016-8e47-47e2-993d-02bdd271b80b.png">

**Comment by cgordon-d2l** [comment]
That didn't jump out at me as as link to source. The `edit` link looks like a Wiki Edit link which would make me think it will fix something on this page.  

There is a line on the splash page that the site is dynamically generated, but I don't feel that people read those things. I didn't until I just went back looking for it.  

The edit link takes you here `https://github.com/BrightspaceUI/core/edit/main/components/button/README.md`, but I think a better place would be here `https://github.com/BrightspaceUI/core/edit/main/components/button`.  There's a link to make an edit from there:
![image](https://user-images.githubusercontent.com/83243241/151380725-1c714cf6-dbfe-436c-9b10-fb0f8a72e233.png)

Maybe a footer tag with something like "View the source or suggest an edit [here](https://github.com/BrightspaceUI/core/tree/main/components/button)"

**Comment by geurts** [comment]
Thanks for raising this Chris! We **are** planning on having an explicit link to the repository on each component page -- this is coming really soon :)

Keep the ideas/feedback coming!

**Comment by geurts** [comment]
Absolutely! I find it confusing as well. We hope to surface secondary information about equivalent MVC/Legacy controls on the Daylight site as well, one day (ie- is this `d2l-menu` control available in MVC? What's it called/where do I find it?)

**Comment by dlockhart** [comment]
I think this has been addressed -- the Daylight site now has text that reads "To see the code, check it out on GitHub:" with a link to the code. I'm going to close this but feel free to chat more with Jeff if you disagree.
