### ISSUE TITLE
d2l-filter -- Scrollbar doesn't show up if using the loading state and have many dimension-set-values

### ISSUE THREAD

**Issue by Chebsi** [BrightspaceUI/core#2075]
If you are using a dimension set with many values, and also use the loading state, the dropdown's scrollbar doesn't appear, so you can't see all the values. If you don't use loading, or if you close and reopen the filter, scrolling will work as expected.

Slack thread for context: https://d2l.slack.com/archives/C0PHG3QB0/p1643834555293599
Also interesting as noticed by Annabel it does not happen with the multi-dimension filter, just single dimension.

Here's one example based on the demo filters page.  I've added many items to the demo filter showing the loading state, and the scrollbar won't show up after the filter is done loading.
![filter-demo](https://user-images.githubusercontent.com/1237719/152362680-9421cba9-923a-491f-9fb7-f159324d5e41.gif)

**Comment by annabelsegalld2l** [comment]
Hi Chebsi, this issue should be resolved in core version 1.231.1. Please re-open this issue you have any more trouble with the filter scrollbar 😄
