### ISSUE TITLE
d2l-scroll-wrapper does not work as expected with d2l-list

### ISSUE THREAD

**Issue by MitchelPaulin** [BrightspaceUI/core#2076]
See this branch for how its being used https://github.com/Brightspace/d2l-rubric/tree/US135547-Add-Back-Scroll-Wrapper

The vertical portion will always attempt to scroll even when there is no need, in the screenshot you can see that the group is the correct size with no hidden elements causing the vertical scroll to kick in, so not sure why it does. I found a simple fix, if I just set `overflow-y: hidden` in the scroll wrapper it behaves like it should, though not sure if adding an API option to set the vertical scrolling behavior of the scroll wrapper would be an acceptable solution.

![Animation4](https://user-images.githubusercontent.com/30714020/152378498-f8163fb5-c45e-4bc2-8b45-984534250228.gif)
![Untitled](https://user-images.githubusercontent.com/30714020/152378516-05c8495d-1b5f-46e7-b078-f3ad31163a6b.png)

**Comment by dbatiste** [comment]
This is fixed with the above merged change.
