### ISSUE TITLE
`d2l-list` dragging between two different instances of `d2l-list` shows a blue line even though it should not be possible

### ISSUE THREAD

**Issue by MitchelPaulin** [BrightspaceUI/core#2095]
If you have two instances of `d2l-list` on the same page and try to drag one element from one list to another list the blue line shows up implying it would be possible to do even though it should not be (note: dragging the item to another list is properly rejected, its only a visual bug).

![d2l-list](https://user-images.githubusercontent.com/30714020/153025977-053f2bc4-6320-476f-9a1e-8e0f55aa6394.gif)

**Comment by dbatiste** [comment]
The feature was actually implemented with this in mind - that it would be possible to drag & drop items between any lists on the page, although preventing this behaviour was not because it was thought it would be unlikely that would have multiple lists on the page with drag & drop enabled.

**Comment by dbatiste** [comment]
We can possibly make some changes so that d&d is only valid in the same list hierarchy for now, and figure out the API for x-root-list d&d when the time comes.
