### ISSUE TITLE
`d2l-list` and `d2l-scroll-wrapper`: Dragging to the last spot adds padding causing the scroll wrapper to start vertical scrolling

### ISSUE THREAD

**Issue by MitchelPaulin** [BrightspaceUI/core#2096]
This is likely only a problem with the `padding-type="none"` option. Dragging to the last spot causes the size of the last element to increase slightly and the scroll wrapper to start vertical scrolling creating a stuttering effect. 

#### Known Workaround 
Adding 6px of padding to the last list item can mitigate the issue. 

![Animation5](https://user-images.githubusercontent.com/30714020/153027352-9e112a1f-b291-424f-ba2a-b2b3c2b6707f.gif)

**Comment by dbatiste** [comment]
We've had a bit of conversation on this.  Currently the marker end-caps are 12px high and it requires some whitespace below the last item to display correctly.  We never really expected the list component to be used in this way.  Nevertheless, we are considering some alternate solutions for the end caps and probably moving the marker up further.  For the moment though, I think the app needs to reserve some space for it until we can get a few other list changes done.
