### ISSUE TITLE
`d2l-loading-spinner` background

### ISSUE THREAD

**Issue by christian-bromann** [BrightspaceUI/core#2454]
Currently the background of this web component is hard coded to `#FFF`. It would be great if you could set a background color for this. What do you think?

**Comment by dbatiste** [comment]
This seems worthwhile.  Is there a current need for this?  If so, whereabouts?

**Comment by dlockhart** [comment]
Thanks Christian, closing for now until that comes up as all the uses we have in our product today are on white.
