### ISSUE TITLE
[Localization] Arabic translation for dialog

### ISSUE THREAD

**Issue by maboelsoudd2l** [BrightspaceUI/core#249]
the translation for https://github.com/BrightspaceUI/core/blob/master/components/dialog/dialog.js#L62
isn't the best. Can we change it?

**Comment by dbatiste** [comment]
We certainly can. I copied this from elsewhere in our system, so I think there's likely more than one spot that we'd want to update - I'm not sure where the original translation came from.

**Comment by dlockhart** [comment]
@maboelsoudd2l just circling back on this issue -- do you have a recommendation on what this translation should be instead? We'll need to update this code but also the corresponding translation in the LMS.

**Comment by dlockhart** [comment]
I'm going to close this due to staleness. @maboelsoudd2l if you think this is still an issue, please re-open with a recommendation on what to use instead. Thanks!
