### ISSUE TITLE
Colors.js is not updated with latest WCAG 2.1 color palette refinements

### ISSUE THREAD

**Issue by cheics-d2l** [BrightspaceUI/core#325]
In colors.js, celestine-1 is defined as #005694, but due to our refinements to the color palette in Aug 2019 to align with WCAG 2.1, many colors (including celestine-1) were changed.

Designers will continue to spec colors by name, however, without the palette updates, we will not be able to pass the required colour contrast in all scenarios.

**See:**
http://design.d2l/style/colour/ > Change History > Aug 1, 2019

![image](https://user-images.githubusercontent.com/8430763/71984476-e8763c00-31f6-11ea-9a6e-aff37079d0f2.png)

**Comment by dlockhart** [comment]
Thanks for raising this Colin. I'm not sure what happened here... we made a bunch of palette changes in May but these changes must have been missed. We'll get them updated.

**Comment by dlockhart** [comment]
Resolved by @AllanKerr in #397 in February.
