### ISSUE TITLE
Add d2l-table to core

### ISSUE THREAD

**Issue by BraydonKains** [BrightspaceUI/core#338]
In light of the recent Future Enhancements sections on the README, I thought it would be pertinent to formalize this request in an issue.

On our LitElement product, we tried to use d2l-table and ran into a number of problems with the styles. Particularly, the styles would often not work on all/any of the tables on the page under inconsistent circumstances. We determined that it was likely to do with the `<custom-style>` element that is required to add the table styles onto the page, which do not work well/at all with LitElement. 
When this was last brought up, there were some efforts to lit-ify the styles, but in the interim we wrote our own styles that emulate the d2l-table component's. We would like to move to the official d2l table if ever it became possible.

**Comment by dlockhart** [comment]
Thanks @BraydonKains. Tables are definitely on our list to port as I know you're not the only team to run into difficulties using the Polymer version in Lit. @AdmiralCoco [made an attempt](https://github.com/BrightspaceUI/core/tree/wip/d2l-table-lit) so we have some WIP stuff to start with at least.

**Comment by svanherk** [comment]
I think we can close this one 😄 🎉

**Comment by dlockhart** [comment]
Oh wow yep!
