### ISSUE TITLE
Add a scroll method to dialogs

### ISSUE THREAD

**Issue by zinabat** [BrightspaceUI/core#341]
A **scroll** method would be valuable for dialogs. Currently, there is no way to access the scrollable content panel of a dialog without deep querying.

**Background:** The new Learning Paths feature uses a dialog to add activities to a learning path. Within the dialog, there is a list component with selectable activities, along with a "load more" button at the bottom. When the load more button is pressed, a spinner is revealed, but is partially cut off by the footer of the dialog.

This would be solved by the ability to scroll to the bottom of the content. It may also be helpful to have the ability to scroll to a specific position.

![image (1)](https://user-images.githubusercontent.com/2412740/73371699-0da11c00-4284-11ea-9bed-d675aa40fe28.png)

See also the related PR: [https://github.com/BrightspaceHypermediaComponents/activities/pull/655](url)

**Comment by dbatiste** [comment]
Thanks for adding this Zina.

**Comment by dlockhart** [comment]
I think we're hoping to resolve this by adjusting the load-more paging behaviour in lists such that it uses a disabled button instead of a different sized loading spinner.

Assuming that solves your problem, I'm going to close this issue -- feel free to re-open if that's not true.
