### ISSUE TITLE
collapsible-panel: Support heading level 5 and 6

### ISSUE THREAD

**Issue by tdevos-d2l** [BrightspaceUI/core#3761]
Within CE we are working on making our headings more easily navigable for screen readers. Due to the d2l-rubrics component using the collapsible-panel component and our need to make its heading an `h5`, it is necessary to support this.

![image](https://github.com/BrightspaceUI/core/assets/90270112/92d0a2c9-4615-4678-a809-d52a1cdc0184)

**Comment by tdevos-d2l** [comment]
Looking at the component's code, this shouldn't be too hard. I don't mind getting a PR up for this

**Comment by tdevos-d2l** [comment]
Unless there are other reasons this is not supported.

**Comment by tdevos-d2l** [comment]
I guess core only defines up to `heading4Styles` so that was probably the reasoning... We only need the defined level, not the style so we could just implement the levels up to 6 and only support styles up to 4... but that's a little weird. Unsure!

**Comment by dbatiste** [comment]
Started a thread in Slack so Jeff and Abbie can weigh in if necessary.
