### ISSUE TITLE
Feature Request: Debounce/Throttle utilities

### ISSUE THREAD

**Issue by apalaniuk** [BrightspaceUI/core#388]
In an effort to move away from Polymer utils, it would be helpful to have a common non-Polymer (and, framework-independent) debouncer. ~Probably a class similar to, or matching, the [Polymer 3 debounce API](https://polymer-library.polymer-project.org/3.0/api/utils/debounce) would be perfectly suitable~ (on second thought, that's overcomplicated/clumsy compared to our needs), but if there's something common we do that can be factored in, would be good to consider that also.

Alternately, we could use more standard utility libraries (lodash, underscore, etc.), so long as we standardize.

**Comment by dlockhart** [comment]
Closing this as we're going to start using lodash in core for debounce/throttle, and would recommend others do the same.
