### ISSUE TITLE
Feature request: breadcrumbs

### ISSUE THREAD

**Issue by j3parker** [BrightspaceUI/core#484]
Opening this per "Future Enhancements" in the README.

Is porting breadcrumbs to lit on the roadmap? Would it be made available via core?

**Comment by miadabrin** [comment]
https://github.com/BrightspaceUI/core/pull/649

**Comment by j3parker** [comment]
Thanks! I'd like to use these on [docs.d2l.dev](//docs.d2l.dev) eventually. I've sub'd to your PR.

**Comment by dlockhart** [comment]
These are now part of version `1.57.0`. Thanks @miadabrin!
