### ISSUE TITLE
Ability for some elements to retarget focus

### ISSUE THREAD

**Issue by dlockhart** [BrightspaceUI/core#546]
Here's a very common workflow: a component is clicked, which opens a dialog. Dialog is smart enough to grab the currently active element (using `getComposedActiveElement` in our focus helpers). When the dialog is subsequently closed, focus is returned to that opener. Brilliant!

Except it doesn't work in all scenarios. If the opener is a menu item in a dropdown, the menu will be collapsed later when focus is attempted to be returned. Since the opener is hidden, the attempt fails and focus is lost. 😭 

What should actually happen: focus should return to the dropdown's opener.

I think a good generic solution to this problem would be for certain elements that collapse -- like dropdowns -- to be able to retarget/delegate opener responsibility elsewhere. That way, when dialog goes to find the currently active element, menu/dropdown would point it at ITS opener.

**Comment by svanherk** [comment]
This was fixed by https://github.com/BrightspaceUI/core/pull/1369, right?

**Comment by dlockhart** [comment]
Yep!
