### ISSUE TITLE
Enable Travis CI build configuration validation

### ISSUE THREAD

**Issue by dlockhart** [BrightspaceUI/core#548]
In the settings in Travis CI, there's this setting:

![Screen Shot 2020-05-15 at 4 25 41 PM](https://user-images.githubusercontent.com/5491151/82093265-cb7fd700-96c8-11ea-99cd-ef0e4ca37375.png)

We've disabled it in the core repo as some things in our configuration were breaking the validation. But this setting will eventually be always-ON and enforced, so it would be good to sort out the issues now instead of kicking the can down the road.

**Comment by dbatiste** [comment]
So I confirmed with the travis folks that indeed, the change to no longer upper-case the first letter of stage names is indeed tied into this, which causes the visual-diff bot not to engage in PRs.  To address that particular issue:

1. quick & easy : upper case the first letter of our stage names, in particular the visual-diff stage.
2. not as quick : make the visual-diff bot more tolerant to case

**Comment by dlockhart** [comment]
We're hoping to move to GitHub Actions anyway, so closing.
