### ISSUE TITLE
d2l-button-icon doesn't pass the color property down to d2l-icon

### ISSUE THREAD

**Issue by j3parker** [BrightspaceUI/core#570]
In `<d2l-icon>` you can set `color` in CSS.
By analogy it seems like that should be possible in `<d2l-button-icon>`, but it isn't:

```html
<d2l-icon
    icon="tier1:close-circle"
    style="color: var(--d2l-color-feedback-error)">
</d2l-icon>

<d2l-button-icon
    type="button"
    icon="tier1:close-circle"
    style="color: var(--d2l-color-feedback-error);">
</d2l-button-icon>
```

Result:

![image](https://user-images.githubusercontent.com/597907/82819524-826d1700-9e6e-11ea-9f40-185023382b13.png)

**Comment by dlockhart** [comment]
Interesting! So I _think_ we were being a bit intentional about only having the icon be ferrite, since [the design](http://design.d2l/components/buttons/) kind of specs it out that way. What's your use case for coloured icons?

**Comment by j3parker** [comment]
Just glitter. I'm switching between `tier1:role-switch` and `tier1:close-circle` to cancel it:

![image](https://user-images.githubusercontent.com/597907/82821526-45a31f00-9e72-11ea-85a6-ef5e83258864.png)

It's easier to tell the two states apart with some color (but not required). If we don't want that because of design I'm fine with that!

**Comment by j3parker** [comment]
Here it is with color, in case this screams "obviously wrong" :)

![image](https://user-images.githubusercontent.com/597907/82821748-9e72b780-9e72-11ea-8a3d-39512d55eb1f.png)

**Comment by dlockhart** [comment]
Yeah I'm pretty sure design intentionally wanted the grey icons to avoid having particular ones popping. There's also the accessibility angle, where enough contrast needs to exist between the icon colour and the hover background colour, which we can guarantee by controlling it.

I'd also worry that if we supported this, then suddenly colours set on parent elements would start bleeding into our icons everywhere, without us actually wanting it to happen. i.e.

```
<div style="color:pink">
    Pink text
    <d2l-icon></d2l-icon>
</div>
```

**Comment by j3parker** [comment]
Ok, cool!

Ah that cascading thing is definitely not pretty.
