### ISSUE TITLE
Selecting d2l-menu-item-radio Closes Containing d2l-menu

### ISSUE THREAD

**Issue by Jevan5** [BrightspaceUI/core#857]
# Selecting d2l-menu-item-radio Closes Containing d2l-menu
## What do we want to do?
Have the containing `<d2l-menu>` close when one of its immediate inner `<d2l-menu-item-radio>`'s is selected.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/24978103/93638830-028f2d80-f9c6-11ea-926b-2360b8f767ff.gif)

## Why do we want to do this?
Only one of the `<d2l-menu-item-radio>`'s in a `<d2l-menu>` can be selected. Once one has been selected, the user is finished with the menu. For this reason, the [WAI-ARIA best-practises for menus](https://www.w3.org/TR/wai-aria-practices/#menu) suggests that activating a menu item should close the menu.

## What challenges are involved?
Should there be an attribute flag for this? If there is a use-case where the menu should always be open, this menu should not be closed on selection.

**Comment by Jevan5** [comment]
@dlockhart I have a settings `<d2l-menu>` with 3 `<d2l-menu-item>`'s, as seen in the GIF above. I tried wrapping a `<d2l-dropdown-menu>` with one of the `<d2l-menu-item>`'s, but it does not open on clicking the `<d2l-menu-item>` (I tried with and without a `<d2l-dropdown-button>`).

I can implement the self-closing of the menu in my component by listening to the `d2l-menu-item-change` event on the menu. I just thought it would be worth thinking about for `<d2l-menu>`'s behaviour when a `<d2l-menu-item-radio>` is chosen.

**Comment by dlockhart** [comment]
So the thing about `<d2l-menu>` is that on its own, it doesn't "close" -- it has no concept of closing because you can drop it anywhere on a page. It's only once a menu is placed inside a dropdown that the concept of closing the dropdown exists.

I was able to get this to close just fine when radios are selected:

```html
<d2l-dropdown>
  <button class="d2l-dropdown-opener">Open it!</button>
  <d2l-dropdown-menu>
    <d2l-menu>
      <d2l-menu-item text="Item 1">
        <d2l-menu>
          <d2l-menu-item-radio text="Item 1-1" value="1-1"></d2l-menu-item-radio>
          <d2l-menu-item-radio text="Black Holes" value="1-2"></d2l-menu-item-radio>
        </d2l-menu>
      </d2l-menu-item>
      <d2l-menu-item text="Item 2">...</d2l-menu-item>
    </d2l-menu>
  </d2l-dropdown-menu>
</d2l-dropdown>
```

**Comment by dlockhart** [comment]
@Jevan5 is this still an issue or can we close?

**Comment by Jevan5** [comment]
@dlockhart You can close this. Using your sample code worked
