### ISSUE TITLE
New dependency 'focus-visible' does not meet license requirements

### ISSUE THREAD

**Issue by devpow112** [BrightspaceUI/core#923]
Noticed when running the D2L license checker it fails on a dependency of this package.
```
"focus-visible@5.2.0" doesn't meet license requirements (W3C)
```

**Comment by dbatiste** [comment]
Ref: https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document

The "...without fee or royalty..." is perhaps the concerning part - not sure if that's the reason this license was excluded from our list though.

**Comment by devpow112** [comment]
The license checker is also not part of the CI for this repo. Feels like it would be a good add to catch stuff like this during development. I can work on adding it.

**Comment by devpow112** [comment]
Adding the license checker there are a number of other licenses from dev dependencies that do not meet requirements either 😞
```
>>> Package "axe-core@4.0.2" doesn't meet license requirements (MPL-2.0).
    Repository: https://github.com/dequelabs/axe-core
    Path: C:\D2L\Development\github\BrightspaceUI\core\node_modules\axe-core

>>> Package "bin-links@1.1.8" doesn't meet license requirements (Artistic-2.0).
    Repository: https://github.com/npm/bin-links
    Path: C:\D2L\Development\github\BrightspaceUI\core\node_modules\npm\node_modules\bin-links

>>> Package "focus-visible@5.2.0" doesn't meet license requirements (W3C).
    Repository: https://github.com/WICG/focus-visible
    Path: C:\D2L\Development\github\BrightspaceUI\core\node_modules\focus-visible

>>> Package "gentle-fs@2.3.1" doesn't meet license requirements (Artistic-2.0).
    Repository: https://github.com/npm/gentle-fs
    Path: C:\D2L\Development\github\BrightspaceUI\core\node_modules\npm\node_modules\gentle-fs

>>> Package "npm-lifecycle@3.1.5" doesn't meet license requirements (Artistic-2.0).
    Repository: https://github.com/npm/lifecycle
    Path: C:\D2L\Development\github\BrightspaceUI\core\node_modules\npm\node_modules\npm-lifecycle

>>> Package "npm@6.14.8" doesn't meet license requirements (Artistic-2.0).
    Repository: https://github.com/npm/cli
    Path: C:\D2L\Development\github\BrightspaceUI\core\node_modules\npm

>>> Package "qrcode-terminal@0.12.0" doesn't meet license requirements (Apache 2.0).
    Repository: https://github.com/gtanner/qrcode-terminal
    Path: C:\D2L\Development\github\BrightspaceUI\core\node_modules\npm\node_modules\qrcode-terminal
```

**Comment by dbatiste** [comment]
Hey Devon, I don't think all these dependencies are actually prod dependencies.  i.e. they don't actually get released or imported by consumers of core.

**Comment by devpow112** [comment]
If they are dev only do they not matter? We are still consuming them for our public repository

**Comment by dbatiste** [comment]
Just taking axe for example... we don't use it in our product.  It's part of our tooling for testing core, and other components.

**Comment by dbatiste** [comment]
As to whether they matter or not, that is a good question.  I guess it depends on the license in question.

**Comment by devpow112** [comment]
Fair enough. Yeah you are correct I believe all of these but the focus visibility one are dev dependencies. What would be the way forward for these then? Can we just ignore them or do we need to get exemptions? Any ideas? I've gotten exemptions for axe on other repos before as an example.

**Comment by devpow112** [comment]
I can pose the question in our open source channel, see if anyone has any input

**Comment by dlockhart** [comment]
Closing, as focus-visible got an exemption.

**Comment by devpow112** [comment]
Thanks @dlockhart completely forgot about this :)
