### ISSUE TITLE
Demo: presetIconLoader.js not found, can't see component demos

### ISSUE THREAD

**Issue by Chebsi** [BrightspaceUI/core#947]
This is my first time using this so I might have messed something up. Also FYI I am not in prod dev so I don't have a dev environment or anything like that set up, if that is necessary. 

Steps I took:
- Cloned this repo
- npm install
- npm start
- selected the 'switch' component on the es-dev-server (locahost:8000) that opened up
- blank screen (same happens when selecting any other component)
- console shows presetIconLoader.js not found, and I could not find it in my cloned repo folder
- specific error from console: 
icon.js:5 GET http://localhost:8000/generated/icons/presetIconLoader.js net::ERR_ABORTED 404 (Not Found)

**Comment by dlockhart** [comment]
You missed one step:
> Run `npm run build` once, or any time icon or Sass files are changed.

**Comment by Chebsi** [comment]
Thanks!!!
